// Code generated by mockery v2.46.0. DO NOT EDIT.

package taskrunner

import (
	context "context"
	json "encoding/json"

	mock "github.com/stretchr/testify/mock"
)

// mockTaskRunner is an autogenerated mock type for the TaskRunner type
type mockTaskRunner struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *mockTaskRunner) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Run provides a mock function with given fields: ctx, args
func (_m *mockTaskRunner) Run(ctx context.Context, args json.RawMessage) error {
	ret := _m.Called(ctx, args)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, json.RawMessage) error); ok {
		r0 = rf(ctx, args)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockTaskRunner creates a new instance of mockTaskRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockTaskRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockTaskRunner {
	mock := &mockTaskRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
