github_checks:
  annotations: false
ignore:
  - "**/mock.go"
  - "**/*_mock.go"
  - "**/init.go"
coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
