// Code generated by mockery v2.46.0. DO NOT EDIT.

package medias

import (
	context "context"
	io "io"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/Peltoche/onlyfun/internal/tools/uuid"
)

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

// Delete provides a mock function with given fields: ctx, fileID
func (_m *MockService) Delete(ctx context.Context, fileID uuid.UUID) error {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, fileID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Download provides a mock function with given fields: ctx, id
func (_m *MockService) Download(ctx context.Context, id uuid.UUID) (io.ReadSeekCloser, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 io.ReadSeekCloser
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (io.ReadSeekCloser, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) io.ReadSeekCloser); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadSeekCloser)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetadata provides a mock function with given fields: ctx, fileID
func (_m *MockService) GetMetadata(ctx context.Context, fileID uuid.UUID) (*FileMeta, error) {
	ret := _m.Called(ctx, fileID)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadata")
	}

	var r0 *FileMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*FileMeta, error)); ok {
		return rf(ctx, fileID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *FileMeta); ok {
		r0 = rf(ctx, fileID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, fileID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetMetadataByChecksum provides a mock function with given fields: ctx, checksum
func (_m *MockService) GetMetadataByChecksum(ctx context.Context, checksum string) (*FileMeta, error) {
	ret := _m.Called(ctx, checksum)

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataByChecksum")
	}

	var r0 *FileMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*FileMeta, error)); ok {
		return rf(ctx, checksum)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *FileMeta); ok {
		r0 = rf(ctx, checksum)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, checksum)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upload provides a mock function with given fields: ctx, mediaType, r
func (_m *MockService) Upload(ctx context.Context, mediaType MediaType, r io.Reader) (*FileMeta, error) {
	ret := _m.Called(ctx, mediaType, r)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 *FileMeta
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, MediaType, io.Reader) (*FileMeta, error)); ok {
		return rf(ctx, mediaType, r)
	}
	if rf, ok := ret.Get(0).(func(context.Context, MediaType, io.Reader) *FileMeta); ok {
		r0 = rf(ctx, mediaType, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*FileMeta)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, MediaType, io.Reader) error); ok {
		r1 = rf(ctx, mediaType, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
