// Code generated by mockery v2.46.0. DO NOT EDIT.

package moderations

import (
	context "context"

	sqlstorage "github.com/Peltoche/onlyfun/internal/tools/sqlstorage"
	mock "github.com/stretchr/testify/mock"
)

// mockStorage is an autogenerated mock type for the storage type
type mockStorage struct {
	mock.Mock
}

// GetAll provides a mock function with given fields: ctx, cmd
func (_m *mockStorage) GetAll(ctx context.Context, cmd *sqlstorage.PaginateCmd) ([]Moderation, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []Moderation
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlstorage.PaginateCmd) ([]Moderation, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlstorage.PaginateCmd) []Moderation); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]Moderation)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlstorage.PaginateCmd) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: ctx, m
func (_m *mockStorage) Save(ctx context.Context, m *Moderation) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Moderation) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newMockStorage creates a new instance of mockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockStorage {
	mock := &mockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
